Makefiles quite ok now, I think...
Try them!

diff --git a/electrotest/src/Makefile b/electrotest/src/Makefile
--- a/electrotest/src/Makefile
+++ b/electrotest/src/Makefile
@@ -1,16 +1,48 @@
+# Targets:
+#
+# all
+#     Rebuild libs if necessary, and link them locally to LOCALLY_LINKED_VERSION. 
+#     NB, this is not exactly according to the specification, but we think this
+#     is a better solution. electrotest is a test suite for the libs, so it shall
+#     rebuild the libs if necessary, and it does build with the .so files, but it fetches
+#     them directly from respective lib, not from a lib folder under electrotest.
+#     Hope this is ok.
+#
+# lib
+#     Rebuild all libs if necessary
+#
+# install_libs
+#     Rebuilds all libs if necessary, and installs them in /usr/lib.
+# 
+# install
+#     Runs the install_libs target, and then rebuilds electrocalc and installs it 
+#     in /usr/bin.
+# 
+# electrotest_local
+#     Builds electrotest_local, i.e. a program with locally linked libs taken from 
+#     the folders at ../..
+# 
+# electrotest
+#     A globally linked version. Libs must be in /usr/lib to run the program.
+#
+# run
+#     Build electrotest_local and run it. 
+#
+# clean
+#     Yep!
+#
+
 ROOT_DIR := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))
 
 INCLUDES=-I$(ROOT_DIR)/../../libresistance/include 
 
 OBJS=$(ROOT_DIR)/electrotest.o
-LOCAL_LIBS=$(ROOT_DIR)/../../libresistance/src/libresistance.so
-# Add more libs here
 
-LOCALLY_LINKED_VERSION=$(ROOT_DIR)/electrotest_local
-GLOBALLY_LINKED_VERSION=$(ROOT_DIR)/electrotest
+LOCALLY_LINKED_VERSION=electrotest_local
+GLOBALLY_LINKED_VERSION=electrotest
 
 
-.PHONY: all clean run lib install_libs
+.PHONY: all clean run lib install_libs uninstall
 
 all: lib $(LOCALLY_LINKED_VERSION)
 #	cd $(ROOT_DIR) && $(MAKE) -f $(ROOT_DIR)/Makefile $(LOCALLY_LINKED_VERSION)
@@ -30,7 +62,15 @@ install: install_libs $(GLOBALLY_LINKED_VERSION)
         fi
 	cp $(GLOBALLY_LINKED_VERSION) /usr/bin
 
-$(LOCALLY_LINKED_VERSION): $(OBJS) $(LOCAL_LIBS)
+uninstall:
+	@runner=`whoami` ; \
+        if test $$runner != "root" ; \
+        then \
+                echo "ERROR: You are not root. Run 'sudo make $@'"; exit 1; \
+        fi
+	rm /usr/bin/$(GLOBALLY_LINKED_VERSION)
+
+$(LOCALLY_LINKED_VERSION): $(OBJS)
 	gcc $(INCLUDES) -o $(LOCALLY_LINKED_VERSION) $(OBJS) -L$(ROOT_DIR)/../../libresistance/src/ -lresistance -Wl,-rpath=$(ROOT_DIR)/../../libresistance/src/
 
 $(GLOBALLY_LINKED_VERSION): $(OBJS)
@@ -43,5 +83,5 @@ run: all
 	$(LOCALLY_LINKED_VERSION)
 
 clean:
-	rm -f $(LOCALLY_LINKED_VERSION) *.o 
+	rm -f $(LOCALLY_LINKED_VERSION) $(GLOBALLY_LINKED_VERSION) *.o 
 	cd $(ROOT_DIR)/../../libresistance/src && $(MAKE) clean MAKEFLAGS=
diff --git a/libresistance/src/Makefile b/libresistance/src/Makefile
--- a/libresistance/src/Makefile
+++ b/libresistance/src/Makefile
@@ -16,5 +16,13 @@ install: libresistance.so
         fi
 	cp libresistance.so /usr/lib
 
+uninstall:
+	@runner=`whoami` ; \
+        if test $$runner != "root" ; \
+        then \
+                echo "ERROR: You are not root. Run 'sudo make $@'"; exit 1; \
+        fi
+	rm /usr/lib/libresistance.so
+
 clean:
 	rm -f *.o *.so
