Now possible to install libresistance, and electrotest.

diff --git a/electrotest/src/Makefile b/electrotest/src/Makefile
--- a/electrotest/src/Makefile
+++ b/electrotest/src/Makefile
@@ -3,27 +3,45 @@ ROOT_DIR := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))
 INCLUDES=-I$(ROOT_DIR)/../../libresistance/include 
 
 OBJS=$(ROOT_DIR)/electrotest.o
-LIBS=$(ROOT_DIR)/../../libresistance/src/libresistance.so
+LOCAL_LIBS=$(ROOT_DIR)/../../libresistance/src/libresistance.so
+# Add more libs here
 
-.PHONY: all clean run lib
+LOCALLY_LINKED_VERSION=$(ROOT_DIR)/electrotest_local
+GLOBALLY_LINKED_VERSION=$(ROOT_DIR)/electrotest
 
-all: lib
-	cd $(ROOT_DIR) && $(MAKE) -f $(ROOT_DIR)/Makefile electrotest
+
+.PHONY: all clean run lib install_libs
+
+all: lib $(LOCALLY_LINKED_VERSION)
+#	cd $(ROOT_DIR) && $(MAKE) -f $(ROOT_DIR)/Makefile $(LOCALLY_LINKED_VERSION)
 
 lib:
 	cd $(ROOT_DIR)/../../libresistance/src && $(MAKE) all MAKEFLAGS=
 # Add more libs here
 
-electrotest: $(OBJS) $(LIBS)
-	gcc $(INCLUDES) -o $(ROOT_DIR)/electrotest $(OBJS) -L$(ROOT_DIR)/../../libresistance/src/ -lresistance -Wl,-rpath=$(ROOT_DIR)/../../libresistance/src/
+install_libs:
+	cd $(ROOT_DIR)/../../libresistance/src && $(MAKE) install MAKEFLAGS=
+
+install: install_libs $(GLOBALLY_LINKED_VERSION)
+	@runner=`whoami` ; \
+        if test $$runner != "root" ; \
+        then \
+                echo "ERROR: You are not root. Run 'sudo make $@'"; exit 1; \
+        fi
+	cp $(GLOBALLY_LINKED_VERSION) /usr/bin
+
+$(LOCALLY_LINKED_VERSION): $(OBJS) $(LOCAL_LIBS)
+	gcc $(INCLUDES) -o $(LOCALLY_LINKED_VERSION) $(OBJS) -L$(ROOT_DIR)/../../libresistance/src/ -lresistance -Wl,-rpath=$(ROOT_DIR)/../../libresistance/src/
+
+$(GLOBALLY_LINKED_VERSION): $(OBJS)
+	gcc $(INCLUDES) -o $(GLOBALLY_LINKED_VERSION) $(OBJS) -lresistance
 
 %.o: %.c
 	gcc $(INCLUDES) -c $<
 
 run: all
-	./electrotest
+	$(LOCALLY_LINKED_VERSION)
 
 clean:
-	rm -f electrotest *.o 
+	rm -f $(LOCALLY_LINKED_VERSION) *.o 
 	cd $(ROOT_DIR)/../../libresistance/src && $(MAKE) clean MAKEFLAGS=
-	echo $(ROOT_DIR)	
diff --git a/libresistance/src/Makefile b/libresistance/src/Makefile
--- a/libresistance/src/Makefile
+++ b/libresistance/src/Makefile
@@ -1,4 +1,4 @@
-.Phony: all clean
+.Phony: all clean install
 
 all: libresistance.so
 
@@ -7,6 +7,14 @@ libresistance.o:libresistance.c ../include/resistance.h
 
 libresistance.so: libresistance.o
 	gcc -shared -fPIC -o libresistance.so libresistance.o
+
+install: libresistance.so
+	@runner=`whoami` ; \
+        if test $$runner != "root" ; \
+        then \
+                echo "ERROR: You are not root. Run 'sudo make $@'"; exit 1; \
+        fi
+	cp libresistance.so /usr/lib
 
 clean:
 	rm -f *.o *.so
